packages:
  debian:
    enable: true
    app:
      gnomedesktop:
        enable: true
        name: task-gnome-desktop
      germandesktop:
        enable: true
        name: task-german-desktop
      chromium:
        enable: true
        name: chromium
      ublockchromium:
        enable: false
        name: webext-ublock-origin-chromium  
      firefoxesr:
        enable: true
        name: firefox-esr
      ublockfirefox:
        enable: true
        name: webext-ublock-origin-firefox  
      libreoffice:
        enable: true
        name: libreoffice
      mplayer:
        enable: true
        name: mplayer
      vlc:
        enable: true
        name: vlc
      supertux:
        enable: true
        name: supertux
      torcs:
        enable: true
        name: torcs
      gnomeboxes:
        enable: true
        name: gnome-boxes
      gnomebuilder:
        enable: true
        name: gnome-builder
      gnomebluetoothsendto:
        enable: true
        name: gnome-bluetooth-sendto
      gnomeconnections:
        enable: true
        name: gnome-connections
      handbrake:
        enable: true
        name: handbrake
      inkscape:
        enable: true
        name: inkscape
      darktable:
        enable: true
        name: darktable
      scribus:
        enable: true
        name: scribus
      apostrophe:  
        enable: true
        name: apostrophe  
      gnomesoftwarepluginflatpak:
        enable: true
        name: gnome-software-plugin-flatpak
      keepassxc:
        enable: true
        name: keepassxc
      webextkeepassxcbrowser:
        enable: true
        name: webext-keepassxc-browser
      obs-studio:
        enable: true
        name: obs-studio
      golang:
        enable: true
        name: golang
      python3:
        enable: true
        name: python3
      python3venv:
        enable: true
        name: python3-venv
      python3pip:
        enable: true
        name: python3-pip
      rustall:
        enable: true
        name: rust-all
      scratch:
        enable: true
        name: scratch
      alsautils:
        enable: true
        name: alsa-utils
      curl:
        enable: true
        name: curl
      dosfstools:
        enable: true
        name: dosfstools
      ethtool:
        enable: true
        name: ethtool
      htop:
        enable: true
        name: htop
      iw:
        enable: true
        name: iw
      less:
        enable: true
        name: less
      links2:
        enable: true
        name: links2
      jq:
        enable: true
        name: jq
      mc:
        enable: true
        name: mc
      ntfs3g:
        enable: true
        name: ntfs-3g
      screen:
        enable: true
        name: screen
      sm:
        enable: true
        name: sm
      ssh:
        enable: true
        name: ssh
      strace:
        enable: true
        name: strace
      tcpdump:
        enable: true
        name: tcpdump
      tmux:
        enable: true
        name: tmux
      vim:
        enable: true
        name: vim
      wget:
        enable: true
        name: wget
      podman:
        enable: true
        name: podman
      cups:
        enable: true
        name: cups
      firmwareiwlwifi:
        enable: true
        name: firmware-iwlwifi
      firmwaremiscnonfree:
        enable: true
        name: firmware-misc-nonfree
      liveconfig:
        enable: true
        name: live-config
      wpasupplicant:
        enable: true
        name: wpasupplicant
      taskenglish:
        enable: true
        name: task-english
      taskgerman:
        enable: true
        name: task-german
      sysstat:
          enable: true
          name: sysstat
      flatpak:
        enable: true
        name: flatpak
      # for apppackage
      libfuse2:
        enable: true
        name: libfuse2
      # host dig.. 
      dnsutils:
        enable: true
        name: dnsutils
      # parallel compression
      pigz:
        enable: true
        name: pigz
      # troubleshooting
      whois:
        enable: true
        name: whois
      # backup & recovery
      restic:
        enable: true
        name: restic
      # ntp timesync
      systemd-timesyncd:
        enable: true
        name: systemd-timesyncd
      cryptsetup:
        enable: true
        name: cryptsetup
      cryptsetup-initramfs:
        enable: true
        name: cryptsetup-initramfs
      zramtools:
        enable: true
        name: zram-tools
      smbclient:
        enable: true
        name: smbclient
      nfs-common:
        enable: true
        name: nfs-common
      thunderbird:
        enable: true
        name: thunderbird
      nextcloud-desktop:
        enable: true
        name: nextcloud-desktop
      gimp:
        enable: true
        name: gimp
      lm-sensors:
        enable: true
        name: lm-sensors
      awscli:
        enable: true
        name: awscli

  github:
    enable: true
    app:
      rustdesk:
        enable: true
        repo: rustdesk
        org: rustdesk
        artifactsuffix: "-x86_64"
  vendor:
    enable: true
    app:
      zoom:
        name: zoom
        enable: true
      icaclient:
        name: icaclient
        enable: true
      teams:
        name: teams
        enable: true
      vscode:
        name: vscode
        enable: true
      signal:
        name: signal
        enable: true
      edge:
        name: edge
        enable: true
      yubico:
        name: yubico
        enable: true
      drawio:
        name: drawio
        enable: true
      kubectl:
        name: kubectl
        enable: true
      torbrowser:
        name: torbrowser
        enable: true
      epsonscan:
        name: epsonscan
        enable: true
        version: 6.7.70.0
        id: 'f/03/00/16/14/38/7b1780ace96e2c6033bbb667c7f3ed281e4e9f38'
      enpass:
        name: enpass
        enable: false
      owncloud:
        name: owncloud
        enable: false
      webex:
        name: webex
        enable: true

  flatpak:
    enable: true
    flathub:
      enable: true
      app:
        vscode:
          enable: false
          name: com.visualstudio.code
        teams:
          enable: false
          name: com.github.IsmaelMartinez.teams_for_linux
        nextcloud:
          enable: false
          name: com.nextcloud.desktopclient.nextcloud
  gnome-shell:
    enable: true
    extension:
      no-overview:
        enable: true
        id: 4099
      dash-to-dock:
        enable: true
        id: 307
      gtk4-desktop-icons-ng:
        enable: true
        id: 5263
  chromium:
    enable: true
    extension:
      ublock-origin-lite:
        enable: true
        repo: uBOL-home
        org: uBlockOrigin
      keepassxc:
        enable: true
        repo: keepassxc-browser
        org: keepassxreboot